[package]
name = "rust-ca-infrastructure"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
rust-ca-domain = { version =  "0.0.1", path = "../domain" }